#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "Memory hogs:
$(ps axch -o cmd:15,%mem:15 --sort=-%mem | head)"
esac

data=$(free -h | tail -n 2 | head -n 1 | tr -s [:space:] ';')
echo "$(echo $data | cut -d ';' -f 3)/$(echo $data | cut -d ';' -f 2)"

